baseurl = "https://www.rlc4u.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "SinLucidious"
theme = "dream"

# copyright = ""

googleAnalytics = "UA-73611419-1"
#disqusShortname = "SinLucidious"
favicon = "/favicon.ico"
enableRobotsTXT = true

[params]
  author = "Richmond Goh"
  motto = "when the few becomes the many"
  # description = ""
  avatar = "/myavatar.png"
  
  email = "richmondgoh@gmail.com"
  github = "richmondgoh8"
  linkedin = "richmondgoh/?originalSubdomain=sg"
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2015
  aboutHeader = "AboutMe"

  # No of Post per page
  paginate = 4

